//
//  FavouriteListRouter.swift
//  MobileListDisplay
//
//  Created by Sujeet Sinha on 29/9/18.
//  Copyright (c) 2018 Allianz Technology. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol FavouriteListRoutingLogic {
  
}

protocol FavouriteListDataPassing {
  var dataStore: FavouriteListDataStore? { get }
}

class FavouriteListRouter: NSObject, FavouriteListRoutingLogic, FavouriteListDataPassing {
  weak var viewController: FavouriteListViewController?
  var dataStore: FavouriteListDataStore?
  
  // MARK: - Route Functions
  
  // MARK: - Navigate Functions
  
  // MARK: - Passing Data Functions
  
}
