//
//  FavouriteListInteractor.swift
//  MobileListDisplay
//
//  Created by Sujeet Sinha on 29/9/18.
//  Copyright (c) 2018 Allianz Technology. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FavouriteListBusinessLogic {
}

protocol FavouriteListDataStore: class {
  //var name: String { get set }
}

class FavouriteListInteractor: FavouriteListBusinessLogic, FavouriteListDataStore {
  var presenter: FavouriteListPresentationLogic?
  //var name: String = ""
  
  // MARK: - Business Functions
  
}
