//
//  MobileListWorker.swift
//  MobileListDisplay
//
//  Created by Sujeet Sinha on 29/9/18.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//  please "import Result" to easy returning structure
//

import UIKit
import Moya
import Result

class MobileListWorker {
  public init(provider: MoyaProvider<ApiServiceConfigurations> = MoyaProvider<ApiServiceConfigurations>()) {
    self.provider = provider
  }
  var provider: MoyaProvider<ApiServiceConfigurations>
  
  public func getMobileList(completion: @escaping (Result<[Mobile], APIError>) -> Void) {
    
    if !Connectivity.isConnectedToInternet {
      completion(.failure(.noInternet))
      return
    }
    
    provider.request(.getMobileList) { result in
      switch result {
      case .success(let moyaResponse):
        let statusCode = moyaResponse.statusCode
        guard statusCode == 200,
          let mobiles = try? JSONDecoder().decode([Mobile].self, from: moyaResponse.data) else {
            completion(.failure(.serviceError))
            return
        }
        
        guard mobiles.count != 0 else {
          completion(.failure(.noRecord))
          return
        }
        
        completion(.success(mobiles))
      case .failure:
        completion(.failure(.serviceError))
      }
    }
  }
  
  func convertMobileDataToModel(mobiles: [Mobile]) -> [MobileList.MobileInfo] {
    return mobiles.map{ MobileList.MobileInfo(id: $0.id,
                                                 rating: $0.rating,
                                                 name: $0.name,
                                                 description: $0.description,
                                                 thumbImageURL: $0.thumbImageURL,
                                                 price: $0.price)}
  }
  
}
