//
//  MobileListRouter.swift
//  MobileListDisplay
//
//  Created by Sujeet Sinha on 29/9/18.
//  Copyright (c) 2018 Allianz Technology. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol MobileListRoutingLogic {
  
}

protocol MobileListDataPassing {
  var dataStore: MobileListDataStore? { get }
}

class MobileListRouter: NSObject, MobileListRoutingLogic, MobileListDataPassing {
  weak var viewController: MobileListViewController?
  var dataStore: MobileListDataStore?
  
  // MARK: - Route Functions
  
  // MARK: - Navigate Functions
  
  // MARK: - Passing Data Functions
  
}
