//
//  MobileListModels.swift
//  MobileListDisplay
//
//  Created by Sujeet Sinha on 29/9/18.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Result

enum MobileList
{
  struct MobileInfo {
    var id: Int
    var rating: Float
    var name: String
    var description: String
    var thumbImageURL: String
    var price: Float
  }
  
  enum GetMobileList
  {
    struct Request {}
    struct Response {
      var result: Result<[Mobile], APIError>
    }
    struct ViewModel {
      enum GetMobileServiceError: Swift.Error {
        case noRecord
        case noInternet
        case serviceError
      }
      var result: Result<[MobileList.MobileInfo], GetMobileServiceError>
    }
  }
  
  enum GetSortedMobileList
  {
    struct Request {
      var selectedTab: TapOptions
      var sorting: Sorting
    }
    struct Response {
      var mobiles: [Mobile]
    }
    struct ViewModel {
      var mobiles: [MobileList.MobileInfo]
    }
  }
  
  enum SelectedMobile
  {
    struct Request {
      var id: Int
    }
    struct Response {}
    struct ViewModel {}
  }
}

