platform :ios, '9.0'

def sharePods
  pod 'Moya'
  pod 'SWSegmentedControl'
  pod 'RealmSwift'
end

target 'MobileListDisplay' do
  use_frameworks!
  sharePods
  pod 'SVProgressHUD'
  pod 'SDWebImage'
  pod 'iCarousel'
end

target 'MobileListDisplayTests' do
  use_frameworks!
  sharePods
  pod 'Quick'
  pod 'Nimble'
end

target 'MobileListDisplayUITests' do
  use_frameworks!
end
