platform :ios, '9.0'

target 'MobileListDisplay' do
  use_frameworks!
  pod 'Moya'
  pod 'SWSegmentedControl'
  pod 'SVProgressHUD'
  pod 'SDWebImage'
end

target 'MobileListDisplayTests' do
  use_frameworks!
end

target 'MobileListDisplayUITests' do
  use_frameworks!
end
