//
//  MobileDetailsInteractor.swift
//  MobileListDisplay
//
//  Created by Sujeet Sinha on 29/9/18.
//  Copyright (c) 2018 Allianz Technology. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MobileDetailsBusinessLogic {
  func getMobileDetailInfo(request: MobileDetails.GetMobileDetail.Request)
}

protocol MobileDetailsDataStore: class {
  var selectedMobile: Mobile { get set }
}

class MobileDetailsInteractor: MobileDetailsBusinessLogic, MobileDetailsDataStore {
  var presenter: MobileDetailsPresentationLogic?
  var selectedMobile: Mobile = Mobile()
  let mobileDetailWorker: MobileDetailsWorker = MobileDetailsWorker()

  
  // MARK: - Business Functions
  
  func getMobileDetailInfo(request: MobileDetails.GetMobileDetail.Request) {
    mobileDetailWorker.getMobileDetailImages(with: selectedMobile.id) { result in
      switch result {
      case .success(let mobileImages):
        let response = MobileDetails.GetMobileDetail.Response(mobile: self.selectedMobile, imageGallery: mobileImages)
        self.presenter?.presentMobileDetails(response: response)
      case .failure(.noInternet), .failure(.serviceError), .failure(.noRecord):
        self.presenter?.presentMobileDetailError()
      }
    }
  }
  
}
