//
//  MobileDetailsPresenter.swift
//  MobileListDisplay
//
//  Created by Sujeet Sinha on 29/9/18.
//  Copyright (c) 2018 Allianz Technology. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MobileDetailsPresentationLogic {
  func presentMobileDetails(response: MobileDetails.GetMobileDetail.Response)
  func presentMobileDetailError()
}

class MobileDetailsPresenter: MobileDetailsPresentationLogic {
  weak var viewController: MobileDetailsDisplayLogic?

  // MARK: - Presentation Function
  
  func presentMobileDetails(response: MobileDetails.GetMobileDetail.Response) {
    let mobileDetail = MobileDetails.GetMobileDetail.ViewModel.MobileDetail(mobile: response.mobile, imageGallery: response.imageGallery)
    let viewModel = MobileDetails.GetMobileDetail.ViewModel(mobileDetail: mobileDetail)
    viewController?.displayMobileDetail(viewModel: viewModel)
  }
  
  func presentMobileDetailError() {
    viewController?.displayMobileDetailError()
  }
}
