//
//  MobileDetailsWorker.swift
//  MobileListDisplay
//
//  Created by Sujeet Sinha on 29/9/18.
//  Copyright (c) 2018 Allianz Technology. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//  please "import Result" to easy returning structure
//

import Moya
import Result

class MobileDetailsWorker {

  public init(provider: MoyaProvider<ApiServiceConfigurations> = MoyaProvider<ApiServiceConfigurations>()) {
    self.provider = provider
  }
  var provider: MoyaProvider<ApiServiceConfigurations>
  
  public func getMobileDetailImages(with mobileId: Int,
                              completion: @escaping (Result<[MobileDetailImages], APIError>) -> Void) {
    
    if !Connectivity.isConnectedToInternet {
      completion(.failure(.noInternet))
      return
    }
    
    provider.request(.getMobileDetailImages(mobileId: mobileId)) { result in
      switch result {
      case .success(let moyaResponse):
        let statusCode = moyaResponse.statusCode
        guard statusCode == 200,
          let mobileImages = try? JSONDecoder().decode([MobileDetailImages].self, from: moyaResponse.data) else {
            completion(.failure(.serviceError))
            return
        }
        
        guard mobileImages.count != 0 else {
          completion(.failure(.noRecord))
          return
        }
        
        completion(.success(mobileImages))
      case .failure:
        completion(.failure(.serviceError))
      }
    }
  }
  
}

